### ISSUE TITLE
Intent transferable crash

### ISSUE THREAD

**Issue by kancic** [blinkcard/blinkcard-android#39]
### Description

We are encountering a crash that we cannot reproduce, and it is currently our biggest issue reported in Crashlytics. The crash occurs with BlinkCard library version 2.9.3 and it has also happened with older versions. 

### Environment Details

**BlinkCard version: 2.9.3**

**Device model: Samsung, Xiaomi, Huawei**

**Device Android version: Mostly Android 12, 10, 14 & 11 (in that order) **

**Device ABI: All Arm devices**

### Stack trace

> Caused by java.lang.IllegalStateException: Intent transferable object cannot be loaded.
>        at com.microblink.blinkcard.intent.BaseIntentTransferable.loadFromIntent(line:76)
>        at com.microblink.blinkcard.uisettings.BlinkCardUISettings.<init>(line:5)
>        at com.microblink.blinkcard.activity.BlinkCardActivity.llIIlIlIIl(line:1)
>        at com.microblink.blinkcard.activity.BaseScanActivity.onCreate(line:1)
>        at com.microblink.blinkcard.activity.BlinkCardActivity.onCreate(line:1)
>        at android.app.Activity.performCreate(Activity.java:8290)
>        at android.app.Activity.performCreate(Activity.java:8270)
>        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
>        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6429)
>        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6294)
>        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
>        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
>        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:65)
>        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6383)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2453)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8751)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
       
### Additional information

The crash seems to be related to the IntentDataTransferMode. We have tried both OPTIMISED and the default PERSISTED_OPTIMISED modes, and the issue persists. 

Any guidance or suggestions on how to address this issue would be greatly appreciated.

**Comment by somyaguptagit** [comment]
Hello @kancic Thank you for reporting the issue!
Could you kindly forward this report to support@microblink.com so that we can investigate it further and gather additional details regarding the crash?
